### ISSUE TITLE
HttpResponse objects do not support equality checks

### ISSUE THREAD

**Issue by danballance** [kodemore/chocs#37]
In my automated tests I'd like to compare the `HttpResponse` that a controller returns with the expected `HttpResponse` that I set up in my test. However this doesn't seem possible because HttpResponse objects use object identity for equality checks:

```
>>> from chocs import HttpResponse, HttpStatus
>>> HttpResponse(status=HttpStatus.OK) == HttpResponse(status=HttpStatus.OK)
False
```

Here's an example of a pytest assertion failure:
```
assert <chocs.http_response.HttpResponse object at 0x10d0389d0> == <chocs.http_response.HttpResponse object at 0x10d240880>
```

What do you think about making these classes more like dataclasses in this regard? (Value objects?)

**Comment by dkraczkowski** [comment]
@danballance how do you think how cookies, headers and body should be compared?

**Comment by dkraczkowski** [comment]
I decided to compare the size of body but not the contents: https://github.com/kodemore/chocs/pull/36/commits/4fe510f10ce0a9f8556cab3c928f373f69c6f6c9

**Comment by dkraczkowski** [comment]
Fixed

**Comment by dkraczkowski** [comment]
https://github.com/kodemore/chocs/actions/runs/401575704
