### ISSUE TITLE
init_dataclass() fails when initialising some Optional types

### ISSUE THREAD

**Issue by stortiz-lifeworks** [kodemore/chocs#78]
I've noticed that init_dataclass fails to initialise a dataclass with Optional types for `ObjectId` or `enum classes`, but works fine with others like `str`

```Python
from dataclasses import dataclass
from enum import Enum
from typing import Optional

from chocs.dataclasses import init_dataclass


class MyEnum(Enum):
    ELEM = 'hello'


@dataclass
class TestOk:
    something: MyEnum


@dataclass
class TestFails:
    something: Optional[MyEnum]


print(init_dataclass({"something": "hello"}, TestOk))
print(init_dataclass({"something": "hello"}, TestFails))

```

The following example fails when initialising `TestFails` when using the enum defined above, but works if I replace the enum type in the dataclass definition by `str`.

I see the same problem when using `ObjectId`

**Comment by dkraczkowski** [comment]
Fixed here: https://github.com/kodemore/chili/blob/main/tests/issues/test_optional_enum_issue.py

Middleware are now moved to separate repos for easier maintenance ;)
