### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by bouh2** [kodemore/chocs#87]
A tiny change to README.

Chocs installation depends on `bjoern` lib. 
`Bjoern` build fails on Ubuntu as it's required additional lib `libev-dev`

Pls., add install of lib `libev-dev` in the README.
`apt install -y libev-dev`

Bjoern issue discussion:
https://github.com/jonashaag/bjoern/issues/166

**Comment by dkraczkowski** [comment]
@bouh2 Added: https://github.com/kodemore/chocs/wiki/WSGI-Integration
